package com.crm.dto;

import com.crm.enums.SalesStage;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.validation.annotation.Validated;

import java.math.BigDecimal;
import java.time.LocalDate;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Validated
public class SalesOpportunityRequestDTO {
    @Schema(name = "opportunityID", description = "Autogenerated value, should not be added.", defaultValue = "null", requiredMode = Schema.RequiredMode.NOT_REQUIRED, hidden = true)
    private Long opportunityID;
    @NotNull(message = "Customer ID can not be null")
    @Min(value = 1, message = "Customer ID must be greater than 0")
    @Schema(name = "customerID", description = "Should be a valid Customer ID", requiredMode = Schema.RequiredMode.REQUIRED)
    private Long customerID;

    @NotNull(message = "Sales Stage cannot be null")
    @Schema(name = "salesStage", description = "Status of LEAD, can be PROSPECTING/QUALIFICATION/CLOSED_WON/CLOSED_LOST", requiredMode = Schema.RequiredMode.REQUIRED)
    private SalesStage salesStage;

    @NotNull(message = "Please enter estimated value.")
    @Min(value = 1, message = "Estimated Value must be greater than 0")
    @Schema(name = "estimatedValue", description = "Should be a big number", requiredMode = Schema.RequiredMode.REQUIRED)
    private BigDecimal estimatedValue;

    @NotNull(message = "Please enter proper date.")
    @Schema(name = "closingDate", description = "Represents the closing date of Lead, should be valid Date in MM/DD/YYYY format", requiredMode = Schema.RequiredMode.REQUIRED)
    private LocalDate closingDate;

    @Schema(name = "followUpReminder", description = "Follow up reminder, should be Date", requiredMode = Schema.RequiredMode.NOT_REQUIRED, hidden = true)
    private LocalDate followUpReminder;
}
