package com.crm.dto;

import com.crm.enums.SalesStage;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.validation.annotation.Validated;

import java.math.BigDecimal;
import java.time.LocalDate;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Validated
public class SalesOpportunityResponseDTO {
    @Schema(name = "Opportunity ID", description = "Autogenerated value, should not be added.", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    private Long opportunityID;
    @Schema(name = "Customer ID", description = "Should be a valid Customer ID", requiredMode = Schema.RequiredMode.REQUIRED)
    private Long customerID;
    @Schema(name = "Sales Stage", description = "Status of LEAD, can be PROSPECTING/QUALIFICATION/CLOSED_WON/CLOSED_LOST", requiredMode = Schema.RequiredMode.REQUIRED)
    private SalesStage salesStage;
    @Schema(name = "Estimated Value", description = "Should be a big number", requiredMode = Schema.RequiredMode.REQUIRED)
    private BigDecimal estimatedValue;
    @Schema(name = "Closing Date", description = "Represents the closing date of Lead, should be valid Date in MM/DD/YYYY format", requiredMode = Schema.RequiredMode.REQUIRED)
    private LocalDate closingDate;
    @Schema(name = "Follow-up reminder", description = "Follow up reminder, should be Date", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    private LocalDate followUpReminder;
}
